# PG'OCaml - type safe interface to PostgreSQL.
# Copyright (C) 2005-2008 Richard Jones and other authors.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this library; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

PACKAGE	:= pgocaml
VERSION	:= 1.2

OCAMLLIBDIR := $(shell ocamlc -where)

# Default location for Unix domain socket directory.  If the auto-detection
# does not work on your system, please set this variable manually.

DEFAULT_UNIX_DOMAIN_SOCKET_DIR := $(if $(wildcard /var/run/postgresql),"/var/run/postgresql","/tmp")
#DEFAULT_UNIX_DOMAIN_SOCKET_DIR := /tmp
#DEFAULT_UNIX_DOMAIN_SOCKET_DIR := /var/run/postgresql


#WINDOWS := 1
