# -*- Makefile -*-
# $Id: Makefile.config,v 1.12 2007-10-28 20:15:26 rich Exp $

PACKAGE	:= pgocaml-monadic
VERSION	:= 1.1

OCAMLLIBDIR := $(shell ocamlc -where)

# Default location for Unix domain socket directory.
# (Use the second option for Debian systems).
#DEFAULT_UNIX_DOMAIN_SOCKET_DIR := /tmp
DEFAULT_UNIX_DOMAIN_SOCKET_DIR := /var/run/postgresql

LWT := 1
#WINDOWS := 1
