# -*- Makefile -*-
# $Id: Makefile.config,v 1.12 2007-10-28 20:15:26 rich Exp $

PACKAGE	:= pgocaml
VERSION	:= 1.0

OCAMLLIBDIR := $(shell ocamlc -where)

# Default location for Unix domain socket directory.
DEFAULT_UNIX_DOMAIN_SOCKET_DIR := /tmp
#DEFAULT_UNIX_DOMAIN_SOCKET_DIR := /var/run/postgresql  <- for Debian

LWT := 1
#WINDOWS := 1
